### PR TITLE
Include jar artifacts.

### LINKED ISSUE #110: Release jar packaged artifact
I looked at the snapshot release and i see it only comes with AAR packaging. Can we get an artifact with simple jar packaging? This way this library could be easily used in eclipse, where there is no way to use AARs. Actually i see no reason to package this library as an AAR, since this contains only classes, no resources, also its nature fits a jar much more.

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #110. Closes #149.

### CODE REVIEW

**Comment by roman-mazur** [comment]
This seems to have removed
```xml
<packaging>aar</packaging>
```
from the POM file.
As a result we get a Gradle build error
```
version com.squareup.assertj:assertj-android-support-v4:1.0.1-SNAPSHOT depends on libraries but is a jar
```

**Comment by roman-mazur** [comment]
The question is will Maven users be able to pick up the jar if packaging is defined as AAR. Because my feeling is that AAR should be the packaging specified in the POM.

**Comment by kriegfrj** [comment]
Maybe this problem could be resolved by publishing the JAR-packaged artifacts under a distinct artifact ID - either instead of, or perhaps in addition to, the artifact ID used by the AAR-packaged artifact?

**Comment by JakeWharton** [comment]
@roman-mazur Yes, by specifying the qualifier.

@kriegfrj I do not want to do that.

**Comment by kriegfrj** [comment]
@JakeWharton: agreed - I offered it as "a" solution though it didn't seem like the most elegant. The qualifier approach should achieve much the same thing but cleaner.

**Pull request merged**
